# services/auth-service/config.yaml

# Common settings
env: "development"
port: "9000"
read_timeout: 5s
request_timeout: 10s
shutdown_timeout: 15s
log_level: "INFO"

# JWT / OAuth2

private_key_path: "/run/secrets/jwt_private.pem"
# Path to the private key used to sign tokens (PEM)
jwks_url: "https://auth.adaptive-learning.com/.well-known/jwks.json"
# Path to the public key or JWKS endpoint (for external validation)
access_token_ttl: 15m
# Access token lifetime
refresh_token_ttl: 168h   # 7 dias
# Refresh token lifetime
issuer: "https://auth.adaptive-learning.com"
# Issuer (iss claim)
audience:
    - "content-engine"
    - "assessment-api"
    - "progress-tracker"

# Audience (aud claim), can be comma-separated or a list
rate_limit: 20       # max 20 req/IP
rate_window: 1m      # janela de 1 minuto

# Rate Limit settings for login routes
cors_origins:
    - "https://app.adaptive-learning.com"

# CORS (if the UI calls directly)
tls_cert_path: "/etc/ssl/certs/tls.crt"
tls_key_path: "/etc/ssl/private/tls.key"
