CREATE SCHEMA IF NOT EXISTS content;
CREATE SCHEMA IF NOT EXISTS assessment;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS progress;
GRANT ALL ON SCHEMA content TO "user";
GRANT ALL ON SCHEMA assessment TO "user";
GRANT ALL ON SCHEMA auth TO "user";
GRANT ALL ON SCHEMA progress TO "user";
